version: '3.8'

services:
  postgres:
    container_name: beauty-app-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: beauty-time
  
  cache:
    container_name: beauty-app-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
